<div class="footer-content">
    <div class="footer-logo">
    </div>
    <div class="footer-links">
        <ul>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">Terms of Use</a></li>
            <li><a href="#">Privacy Policy</a></li>
        </ul>
    </div>
</div>
<div class="footer-bottom">
    <p>© <?php echo date("Y"); ?> Farmacias del Harness. All Rights Reserved.</p>
</div>
